[package]
name = "moving_around"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.17.3", features = ["dynamic_linking", "bevy_remote", "bevy_animation"] }
bevy-inspector-egui = "0.35.0"
bevy_behave = "0.4.0"
bevy_landmass = "0.10.0"
bevy_mod_skinned_aabb = "0.3.0"
bevy_rapier3d = { version = "*", features = ["debug-render-3d"] }
bevy_rerecast = "0.3.0"
landmass_rerecast = "0.1.0"

[patch.crates-io]
bevy_rapier3d = {git = 'https://github.com/dimforge/bevy_rapier.git'}

# Enable a small amount of optimization in the dev profile.
[profile.dev]
opt-level = 1

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3
